#!/usr/bin/env python3
"""Write static/_redirects from data/legacy_redirects.yaml.

The Wowchemy -> Blowfish migration (commit d78f6ba) deleted every old content
page, so the URLs Google and Google Scholar still index all 404. This emits
Netlify 301 rules pointing each one at its closest live equivalent.

Netlify evaluates rules in file order and takes the first match, so every
explicit rule is written above the catch-all for its section.

Hugo copies static/ into public/ verbatim and Netlify reads public/_redirects.
Netlify does not run Python, so the generated file is committed.

Run after editing data/legacy_redirects.yaml:
    python3 scripts/gen_redirects.py

After a Hugo build, check every rule against what was actually rendered:
    hugo --gc --minify && python3 scripts/gen_redirects.py --check
"""
import os
import re
import sys

import yaml

IN_MAP = "data/legacy_redirects.yaml"
IN_PUBS = "data/publications.yaml"
OUT = "static/_redirects"

COL = 46  # column the destination starts at, for a readable diff
PUBLIC = "public"


def check():
    """Validate static/_redirects against a Hugo build in public/.

    Catches the failure that matters: an anchor pointing at something the page
    no longer renders, or a destination path that does not exist. Attribute
    values are matched unquoted too, because --minify strips the quotes.
    """
    if not os.path.isdir(PUBLIC):
        print(f"no {PUBLIC}/ directory. Run `hugo --gc --minify` first.", file=sys.stderr)
        return 1

    def ids_in(path):
        f = os.path.join(PUBLIC, path.strip("/"), "index.html") if path.strip("/") \
            else os.path.join(PUBLIC, "index.html")
        if not os.path.isfile(f):
            return None
        return set(re.findall(r'id=["\']?([A-Za-z0-9_-]+)', open(f, encoding="utf-8").read()))

    cache, bad, n = {}, [], 0
    for line in open(OUT, encoding="utf-8"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        src, dst, _ = line.split()
        n += 1

        path, _, frag = dst.partition("#")
        path = path.split("?")[0] or "/"

        if ":splat" in path:          # destination depends on the request
            continue

        if path not in cache:
            cache[path] = ids_in(path)
        ids = cache[path]

        if ids is None:
            bad.append(f"{src} -> {dst} (no page at {path})")
        elif frag and frag not in ids:
            bad.append(f"{src} -> {dst} (no id={frag!r} on {path})")

    pub_ids = cache.get("/publications/") or set()
    print(f"checked {n} rules against {PUBLIC}/: {len(bad)} broken")
    for b in bad:
        print(f"  {b}", file=sys.stderr)
    print(f"/publications/ renders {len([i for i in pub_ids if i.startswith('pmid-')])} pmid anchors")
    return 1 if bad else 0


def rule(src, dst, code=301):
    return f"{src.ljust(COL)}{dst.ljust(COL)}{code}\n"


def main():
    if "--check" in sys.argv:
        return check()

    m = yaml.safe_load(open(IN_MAP))
    pubs = yaml.safe_load(open(IN_PUBS))["publications"]
    known = {str(p["pmid"]) for p in pubs if p.get("pmid")}

    # Guard against drift: a PMID dropped from the bib would silently produce a
    # redirect to an anchor that no longer renders.
    stale = {s: p for s, p in m["publication"].items() if p not in known}
    if stale:
        print(f"ERROR: {len(stale)} mapped PMIDs are no longer in {IN_PUBS}:", file=sys.stderr)
        for slug, pmid in sorted(stale.items()):
            print(f"  /publication/{slug}/ -> pmid-{pmid}", file=sys.stderr)
        print("Fix data/legacy_redirects.yaml, or move the slug to "
              "publication_unmapped.", file=sys.stderr)
        return 1

    variants = m.get("publication_case_variants") or {}
    out = []
    n = 0

    out.append("""\
# Legacy URL redirects, generated by scripts/gen_redirects.py from
# data/legacy_redirects.yaml. Do not edit by hand.
#
# Every path here was live before the Wowchemy -> Blowfish migration (d78f6ba)
# and 404s now. Rules are ordered: explicit first, catch-all last, because
# Netlify takes the first match.

# -- Publications ------------------------------------------------------------
# Each old per-paper page now anchors into the single /publications/ list.
""")
    for slug, pmid in sorted(m["publication"].items()):
        out.append(rule(f"/publication/{slug}/", f"/publications/#pmid-{pmid}"))
        n += 1
        if slug in variants:
            out.append(rule(f"/publication/{variants[slug]}/", f"/publications/#pmid-{pmid}"))
            n += 1

    out.append("\n# Not in the bib (thesis, book chapter, non-indexed journal).\n")
    for slug in sorted(m.get("publication_unmapped") or []):
        out.append(rule(f"/publication/{slug}/", "/publications/"))
        n += 1
        if slug in variants:
            out.append(rule(f"/publication/{variants[slug]}/", "/publications/"))
            n += 1

    out.append("\n# Anything else under the old publication tree.\n")
    for src in ("/publication/*", "/publication-type/*"):
        out.append(rule(src, "/publications/"))
        n += 1

    out.append("""
# -- Posts -------------------------------------------------------------------
# The section moved from /post/ to /posts/. One slug changed too, so it is
# listed above the splat.
""")
    for slug, dst in sorted((m.get("post") or {}).items()):
        out.append(rule(f"/post/{slug}/", dst))
        n += 1
    out.append(rule("/post/", "/posts/"))
    out.append(rule("/post/*", "/posts/:splat"))
    n += 2

    out.append("""
# -- Tags --------------------------------------------------------------------
# The old taxonomy was /tag/<slug>/ and listed publications. ?q= prefills the
# filter on /publications/, matching against the curated tags in pub_meta.yaml.
""")
    for slug, dst in sorted((m.get("tag") or {}).items()):
        dst = f"/publications/{dst}" if dst.startswith("?q=") else dst
        out.append(rule(f"/tag/{slug}/", dst))
        n += 1
    for src in ("/tag/*", "/category/*"):
        out.append(rule(src, "/publications/"))
        n += 1

    out.append("""
# -- Projects ----------------------------------------------------------------
# Per-project pages are gone. The packages now live in the homepage section.
""")
    for src in ("/project/*", "/software/", "/software/*"):
        out.append(rule(src, "/#software"))
        n += 1

    out.append("""
# -- Talks -------------------------------------------------------------------
# Old permalink was /talk/:slug/; /event/ was the section list. Both collapse
# into the single /talks/ page.
""")
    for src in ("/talk/*", "/event/*"):
        out.append(rule(src, "/talks/"))
        n += 1

    out.append("""
# -- Retired pages -----------------------------------------------------------
# Wowchemy scaffolding and pages with no replacement.
""")
    for src in ("/authors/*", "/admin/*", "/slides/*", "/privacy/", "/terms/", "/home/*"):
        out.append(rule(src, "/"))
        n += 1

    with open(OUT, "w") as f:
        f.writelines(out)

    print(f"wrote {OUT}: {n} rules")
    return 0


if __name__ == "__main__":
    sys.exit(main())
